# Generated by Django 6.0.8 on 2026-08-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LtiCourseContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_site', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('course_title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('moodle_site', 'course_id'), name='uniq_lti_course_context_site_course')],
            },
        ),
    ]
