# Generated by Django 6.0.8 on 2026-08-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticoursecontext',
            name='custom_moodle_site',
            field=models.CharField(help_text='Optional custom Moodle site name for display purposes.', max_length=255, null=True),
        ),
    ]
