# Generated by Django 6.0.8 on 2026-08-05 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lticoursecontext_custom_moodle_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField(blank=True, help_text='Prompt content to send to LLMs.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_prompts', to=settings.AUTH_USER_MODEL)),
                ('last_update', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_prompts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
