# Generated by Django 6.0.8 on 2026-08-05 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255)),
                ('course_title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_site', models.CharField(max_length=255, unique=True)),
                ('custom_moodle_site', models.CharField(blank=True, help_text='Optional display name for this Moodle site.', max_length=255)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='lticoursecontext',
            name='uniq_lti_course_context_site_course',
        ),
        migrations.DeleteModel(
            name='LtiCourseContext',
        ),
        migrations.AddField(
            model_name='question',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='questions', to='app.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app.site'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('site', 'course_title'), name='uniq_course_site_title'),
        ),
    ]
