# Generated by GitHub Copilot on 2026-08-05

import django.db.models.deletion
from django.db import migrations, models


def migrate_question_course_forward(apps, schema_editor):
    Question = apps.get_model('app', 'Question')
    through = Question.courses.through

    for question in Question.objects.all().iterator():
        relation = through.objects.filter(question_id=question.id).order_by('id').first()
        if relation is not None:
            question.course_id = relation.course_id
            question.save(update_fields=['course'])


def migrate_question_course_backward(apps, schema_editor):
    Question = apps.get_model('app', 'Question')
    through = Question.courses.through

    for question in Question.objects.exclude(course_id__isnull=True).iterator():
        through.objects.get_or_create(question_id=question.id, course_id=question.course_id)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='questions',
                to='app.course',
            ),
        ),
        migrations.RunPython(migrate_question_course_forward, migrate_question_course_backward),
        migrations.RemoveField(
            model_name='question',
            name='courses',
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='questions',
                to='app.course',
            ),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='uniq_question_course_title'),
        ),
    ]
