# Generated by Django 6.0.8 on 2026-08-06 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_question_single_course_unique_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='General', help_text='Name of the category.', max_length=255),
        ),
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='question_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='question_pictures/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines the order of the pictures in the body.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='app.question')),
            ],
            options={
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
